"""``tunapi service`` — manage the background launch agent.

On macOS this generates a launchd LaunchAgent plus a small launcher script
so the bridge starts at login, restarts on crash, and can be managed with
``tunapi service {install,start,stop,restart,status,logs,uninstall}`` —
no hand-edited plist required.

Path detection is dynamic (uv, node/fnm, Homebrew) so the agent does not
break when a tool is upgraded; re-run ``tunapi service install`` to refresh.
"""

from __future__ import annotations

import contextlib
import os
import shutil
import signal
import subprocess
import sys
import time
import tomllib
from pathlib import Path

import typer

LABEL = "com.tunapi"


# ---------------------------------------------------------------------------
# Path resolution (pure)
# ---------------------------------------------------------------------------


def plist_path() -> Path:
    return Path.home() / "Library" / "LaunchAgents" / f"{LABEL}.plist"


def launcher_path() -> Path:
    return Path.home() / ".local" / "bin" / "tunapi-launcher.sh"


def log_path() -> Path:
    return Path.home() / ".tunapi" / "service.log"


def config_dir() -> Path:
    return Path.home() / ".tunapi"


def resolve_repo_root() -> Path:
    """Locate the tunapi source checkout (where ``uv run tunapi`` resolves the
    project). Walk up from this module, falling back to the cwd."""
    for parent in Path(__file__).resolve().parents:
        if (parent / "pyproject.toml").is_file():
            return parent
    return Path.cwd()


def resolve_uv() -> str:
    """Absolute path to the ``uv`` binary, or raise a helpful error."""
    found = shutil.which("uv")
    if found:
        return found
    fallback = Path.home() / ".local" / "bin" / "uv"
    if fallback.is_file():
        return str(fallback)
    raise typer.BadParameter(
        "Could not find `uv` on PATH. Install uv first: https://docs.astral.sh/uv/"
    )


def _base_path_entries(uv_path: str) -> list[str]:
    """Directories the launchd agent needs on PATH (launchd starts with a bare
    environment). Ordered, de-duplicated, existing dirs only."""
    home = Path.home()
    candidates = [
        str(Path(uv_path).parent),
        "/opt/homebrew/bin",
        "/opt/homebrew/sbin",
        "/usr/local/bin",
        "/usr/bin",
        "/bin",
        str(home / ".local" / "bin"),
        str(home / ".cargo" / "bin"),
    ]
    seen: set[str] = set()
    ordered: list[str] = []
    for entry in candidates:
        if entry not in seen:
            seen.add(entry)
            ordered.append(entry)
    return ordered


def _node_setup_line() -> str:
    """Shell lines that put the active Node on PATH. Prefer fnm (so Node
    upgrades are picked up automatically), with the install-time node dir as a
    fallback if fnm ever fails to resolve a version."""
    fnm = shutil.which("fnm")
    node = shutil.which("node")
    node_dir = str(Path(node).parent) if node else None
    if fnm:
        lines = [
            f'export PATH="{Path(fnm).parent}:$PATH"',
            'eval "$(fnm env 2>/dev/null)" 2>/dev/null || true',
        ]
        if node_dir:
            lines.append(
                f'command -v node >/dev/null 2>&1 || export PATH="{node_dir}:$PATH"'
            )
        return "\n".join(lines)
    if node_dir:
        return f'export PATH="{node_dir}:$PATH"'
    return "# (node not detected at install time)"


def render_launcher(*, repo: Path, uv_path: str) -> str:
    """Render the launcher shell script."""
    path_env = ":".join(_base_path_entries(uv_path))
    cfg = config_dir()
    return f"""#!/bin/bash
# Generated by `tunapi service install`. Re-run that command to regenerate
# (e.g. after upgrading uv or node). Manual edits will be overwritten.
set -u

# KeepAlive restarts can leave stale transport lock files behind.
rm -f "{cfg}/"*.lock 2>/dev/null || true

export PATH="{path_env}:$PATH"
export HOMEBREW_PREFIX="/opt/homebrew"
{_node_setup_line()}

cd "{repo}" || exit 1
# Run via `uv run`: under launchd the uv executable holds the macOS local
# network grant, so exec'ing the venv binary directly fails to reach LAN hosts
# (EHOSTUNREACH). The orphaned child this can leave is reaped by `service
# stop`/`restart` (see _terminate_stale).
exec "{uv_path}" run tunapi
"""


def render_plist(*, launcher: Path, repo: Path, log: Path) -> str:
    """Render the launchd plist XML."""
    home = str(Path.home())
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{LABEL}</string>

    <key>ProgramArguments</key>
    <array>
        <string>{launcher}</string>
    </array>

    <key>WorkingDirectory</key>
    <string>{repo}</string>

    <key>RunAtLoad</key>
    <true/>

    <key>KeepAlive</key>
    <true/>

    <key>ThrottleInterval</key>
    <integer>10</integer>

    <key>ExitTimeOut</key>
    <integer>15</integer>

    <key>StandardOutPath</key>
    <string>{log}</string>

    <key>StandardErrorPath</key>
    <string>{log}</string>

    <key>EnvironmentVariables</key>
    <dict>
        <key>HOME</key>
        <string>{home}</string>
    </dict>
</dict>
</plist>
"""


# ---------------------------------------------------------------------------
# launchd interaction (side effects)
# ---------------------------------------------------------------------------


def _domain() -> str:
    return f"gui/{os.getuid()}"


def _service_target() -> str:
    return f"{_domain()}/{LABEL}"


def _launchctl(*args: str, check: bool = False) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["launchctl", *args],
        capture_output=True,
        text=True,
        check=check,
    )


def _is_loaded() -> bool:
    return _launchctl("print", _service_target()).returncode == 0


def _bootout() -> None:
    _launchctl("bootout", _service_target())


def _bootstrap() -> subprocess.CompletedProcess[str]:
    return _launchctl("bootstrap", _domain(), str(plist_path()))


def _tunadish_port() -> int:
    """The tunadish websocket port from config (default 8765). Matched against
    listeners so we reap only the actual worker, never the CLI invoking us."""
    cfg = config_dir() / "tunapi.toml"
    with contextlib.suppress(Exception):
        data = tomllib.loads(cfg.read_text(encoding="utf-8"))
        transports = data.get("transports", {})
        td = transports.get("tunadish", {}) if isinstance(transports, dict) else {}
        port = td.get("port") if isinstance(td, dict) else None
        if isinstance(port, int):
            return port
    return 8765


def _port_listeners(port: int) -> list[int]:
    try:
        out = subprocess.run(
            ["lsof", "-nP", f"-tiTCP:{port}", "-sTCP:LISTEN"],
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        return []
    return [int(x) for x in out.stdout.split() if x.strip().isdigit()]


def _terminate_stale() -> None:
    """Kill a leftover worker still holding the tunadish port. launchctl
    bootout can orphan the uv-spawned child (reparented to launchd), which then
    blocks the next start. Matching by listening port — not by command line —
    avoids killing the CLI process that is running this command."""
    me = os.getpid()
    for pid in _port_listeners(_tunadish_port()):
        if pid != me:
            with contextlib.suppress(ProcessLookupError, PermissionError):
                os.kill(pid, signal.SIGKILL)


def _wait_unloaded(timeout_s: float = 6.0) -> None:
    """Poll until the agent is fully unloaded (bootout is asynchronous; a
    bootstrap that races it fails with EIO)."""
    for _ in range(int(timeout_s * 5)):
        if not _is_loaded():
            return
        time.sleep(0.2)


def _bootout_and_reap() -> None:
    """Unload the agent (if loaded), wait for it to settle, and reap any
    orphaned worker."""
    if _is_loaded():
        _bootout()
        _wait_unloaded()
    _terminate_stale()


def _bootstrap_retry(attempts: int = 5) -> subprocess.CompletedProcess[str]:
    """Bootstrap, retrying on the transient EIO launchd returns right after a
    bootout."""
    result = _bootstrap()
    for _ in range(attempts - 1):
        if result.returncode == 0:
            return result
        time.sleep(1.0)
        result = _bootstrap()
    return result


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------


def service_install(
    force: bool = typer.Option(
        False, "--force", help="Overwrite an existing launcher/plist without asking."
    ),
) -> None:
    """Generate and load the background launch agent (macOS launchd)."""
    _require_macos_or_exit()

    repo = resolve_repo_root()
    uv_path = resolve_uv()
    plist = plist_path()
    launcher = launcher_path()
    log = log_path()

    if plist.exists() and not force:
        typer.echo(f"{plist} already exists. Re-run with --force to regenerate.")
        raise typer.Exit(code=1)

    launcher.parent.mkdir(parents=True, exist_ok=True)
    plist.parent.mkdir(parents=True, exist_ok=True)
    log.parent.mkdir(parents=True, exist_ok=True)

    launcher.write_text(render_launcher(repo=repo, uv_path=uv_path), encoding="utf-8")
    launcher.chmod(0o755)
    plist.write_text(
        render_plist(launcher=launcher, repo=repo, log=log), encoding="utf-8"
    )

    # Reload cleanly; reap any orphaned worker holding the port.
    _bootout_and_reap()
    result = _bootstrap_retry()
    if result.returncode != 0:
        typer.echo(
            f"launchctl bootstrap failed: {result.stderr.strip() or result.returncode}",
            err=True,
        )
        raise typer.Exit(code=1)

    typer.echo(f"installed launch agent {LABEL}")
    typer.echo(f"  launcher: {launcher}")
    typer.echo(f"  plist:    {plist}")
    typer.echo(f"  repo:     {repo}")
    typer.echo(f"  logs:     {log}")
    typer.echo("running. check status with `tunapi service status`.")


def service_uninstall() -> None:
    """Unload and remove the background launch agent."""
    _require_macos_or_exit()
    if _is_loaded():
        _bootout()
    removed = []
    for path in (plist_path(), launcher_path()):
        if path.exists():
            path.unlink()
            removed.append(str(path))
    if removed:
        typer.echo("removed:\n  " + "\n  ".join(removed))
    else:
        typer.echo("nothing to remove.")


def service_start() -> None:
    """Start (bootstrap) the launch agent."""
    _require_macos_or_exit()
    if not plist_path().exists():
        typer.echo("not installed. run `tunapi service install` first.", err=True)
        raise typer.Exit(code=1)
    if _is_loaded():
        typer.echo("already running.")
        return
    result = _bootstrap_retry()
    if result.returncode != 0:
        typer.echo(result.stderr.strip() or "failed to start.", err=True)
        raise typer.Exit(code=1)
    typer.echo("started.")


def service_stop() -> None:
    """Stop (bootout) the launch agent."""
    _require_macos_or_exit()
    if not _is_loaded():
        typer.echo("not running.")
        return
    _bootout_and_reap()
    typer.echo("stopped.")


def service_restart() -> None:
    """Restart the running launch agent."""
    _require_macos_or_exit()
    if not plist_path().exists():
        typer.echo("not installed. run `tunapi service install` first.", err=True)
        raise typer.Exit(code=1)
    # Full bootout+reap+bootstrap (kickstart would orphan the uv-run child).
    _bootout_and_reap()
    result = _bootstrap_retry()
    if result.returncode != 0:
        typer.echo(result.stderr.strip() or "failed to restart.", err=True)
        raise typer.Exit(code=1)
    typer.echo("restarted.")


def service_status() -> None:
    """Show whether the launch agent is loaded and tail recent logs."""
    _require_macos_or_exit()
    if not plist_path().exists():
        typer.echo("not installed. run `tunapi service install` first.")
        raise typer.Exit(code=1)
    loaded = _is_loaded()
    typer.echo(f"{LABEL}: {'running' if loaded else 'installed (not loaded)'}")
    log = log_path()
    if log.exists():
        typer.echo(f"\nlast log lines ({log}):")
        lines = log.read_text(encoding="utf-8", errors="replace").splitlines()
        for line in lines[-10:]:
            typer.echo(f"  {line}")


def service_logs(
    follow: bool = typer.Option(
        False, "--follow", "-f", help="Follow the log (like tail -f)."
    ),
) -> None:
    """Print (or follow) the service log."""
    _require_macos_or_exit()
    log = log_path()
    if not log.exists():
        typer.echo(f"no log yet at {log}.")
        return
    if follow:
        subprocess.run(["tail", "-f", str(log)])
        return
    subprocess.run(["tail", "-n", "50", str(log)])


def _require_macos_or_exit() -> None:
    if sys.platform != "darwin":
        typer.echo(
            "service management currently supports macOS (launchd) only.", err=True
        )
        raise typer.Exit(code=1)


def build_service_app() -> typer.Typer:
    app = typer.Typer(help="Manage the background launch agent (macOS launchd).")
    app.command(name="install")(service_install)
    app.command(name="uninstall")(service_uninstall)
    app.command(name="start")(service_start)
    app.command(name="stop")(service_stop)
    app.command(name="restart")(service_restart)
    app.command(name="status")(service_status)
    app.command(name="logs")(service_logs)
    return app
